import type { User, Category, Gig, Order, Review } from "./types"

export const mockUsers: User[] = [
  {
    id: "user1",
    email: "alice@example.com",
    full_name: "Alice Smith",
    avatar_url: "/placeholder.svg?height=40&width=40",
    college: "Pune Institute of Technology",
    major: "Computer Science",
    year: "3rd Year",
    city: "Pune",
    bio: "Passionate web developer with expertise in React and Node.js. Love creating beautiful and functional websites.",
    skills: ["React", "Node.js", "JavaScript", "TypeScript", "MongoDB"],
    is_verified: true,
    reputation_score: 85,
    total_earnings: 25000,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-20T15:30:00Z",
  },
  {
    id: "user2",
    email: "bob@example.com",
    full_name: "Bob Johnson",
    avatar_url: "/placeholder.svg?height=40&width=40",
    college: "Symbiosis Institute of Technology",
    major: "Graphic Design",
    year: "2nd Year",
    city: "Pune",
    bio: "Creative graphic designer specializing in brand identity and digital marketing materials.",
    skills: ["Photoshop", "Illustrator", "Figma", "Brand Design", "UI/UX"],
    is_verified: false,
    reputation_score: 72,
    total_earnings: 18000,
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-01-18T12:00:00Z",
  },
  {
    id: "user3",
    email: "charlie@example.com",
    full_name: "Charlie Brown",
    avatar_url: "/placeholder.svg?height=40&width=40",
    college: "MIT World Peace University",
    major: "Marketing",
    year: "4th Year",
    city: "Pune",
    bio: "Digital marketing enthusiast with experience in social media management and content creation.",
    skills: ["Social Media", "Content Writing", "SEO", "Google Ads", "Analytics"],
    is_verified: true,
    reputation_score: 90,
    total_earnings: 32000,
    created_at: "2024-01-05T09:00:00Z",
    updated_at: "2024-01-22T14:00:00Z",
  },
]

export const mockCategories: Category[] = [
  {
    id: "cat1",
    name: "Web Development",
    description: "Frontend and backend web development services",
    color: "#3B82F6",
    icon: "Code",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat2",
    name: "Graphic Design",
    description: "Logo design, branding, and visual content creation",
    color: "#EF4444",
    icon: "Palette",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat3",
    name: "Digital Marketing",
    description: "Social media management, SEO, and online advertising",
    color: "#10B981",
    icon: "TrendingUp",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat4",
    name: "Content Writing",
    description: "Blog posts, articles, and copywriting services",
    color: "#F59E0B",
    icon: "PenTool",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat5",
    name: "Mobile Apps",
    description: "iOS and Android app development",
    color: "#8B5CF6",
    icon: "Smartphone",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat6",
    name: "Data Analysis",
    description: "Data visualization and statistical analysis",
    color: "#06B6D4",
    icon: "BarChart",
    created_at: "2024-01-01T00:00:00Z",
  },
]

export const mockGigs: Gig[] = [
  {
    id: "gig1",
    user_id: "user1",
    category_id: "cat1",
    title: "I will create a modern React website for your business",
    description:
      "Professional React website with responsive design, modern UI/UX, and optimized performance. Perfect for small to medium businesses looking to establish their online presence.",
    price: 15000,
    delivery_days: 7,
    rating: 4.8,
    total_orders: 23,
    tags: ["React", "JavaScript", "Responsive", "Modern"],
    requirements: "Provide business details, preferred colors, and any specific requirements",
    is_active: true,
    gig_type: "service",
    collaboration_type: "individual",
    skill_level: "advanced",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-20T15:30:00Z",
    user: mockUsers[0],
    category: mockCategories[0],
  },
  {
    id: "gig2",
    user_id: "user2",
    category_id: "cat2",
    title: "Professional logo design for your brand",
    description:
      "Custom logo design that represents your brand identity. Includes multiple concepts, revisions, and final files in various formats.",
    price: 5000,
    delivery_days: 3,
    rating: 4.9,
    total_orders: 45,
    tags: ["Logo", "Branding", "Creative", "Professional"],
    requirements: "Brand name, industry, preferred style, and color preferences",
    is_active: true,
    gig_type: "service",
    collaboration_type: "individual",
    skill_level: "intermediate",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-01-18T12:00:00Z",
    user: mockUsers[1],
    category: mockCategories[1],
  },
  {
    id: "gig3",
    user_id: "user3",
    category_id: "cat3",
    title: "Social media marketing strategy and management",
    description:
      "Complete social media strategy including content calendar, post creation, and engagement management for Instagram, Facebook, and LinkedIn.",
    price: 8000,
    delivery_days: 5,
    rating: 4.7,
    total_orders: 32,
    tags: ["Social Media", "Marketing", "Strategy", "Content"],
    requirements: "Business details, target audience, and current social media accounts",
    is_active: true,
    gig_type: "service",
    collaboration_type: "individual",
    skill_level: "advanced",
    created_at: "2024-01-05T09:00:00Z",
    updated_at: "2024-01-22T14:00:00Z",
    user: mockUsers[2],
    category: mockCategories[2],
  },
  {
    id: "gig4",
    user_id: "user1",
    category_id: "cat5",
    title: "Need a mobile app developer for e-commerce project",
    description:
      "Looking for an experienced React Native developer to build a cross-platform e-commerce mobile application with payment integration.",
    price: 50000,
    delivery_days: 21,
    rating: 0,
    total_orders: 0,
    tags: ["React Native", "E-commerce", "Mobile", "Payment"],
    requirements: "Experience with React Native, payment gateways, and e-commerce platforms",
    is_active: true,
    gig_type: "request",
    collaboration_type: "individual",
    skill_level: "advanced",
    created_at: "2024-01-25T11:00:00Z",
    updated_at: "2024-01-25T11:00:00Z",
    user: mockUsers[0],
    category: mockCategories[4],
  },
  {
    id: "gig5",
    user_id: "user2",
    category_id: "cat4",
    title: "Blog content writing for tech startup",
    description:
      "Professional blog posts about technology trends, startup insights, and industry analysis. SEO optimized content that engages readers.",
    price: 3000,
    delivery_days: 2,
    rating: 4.6,
    total_orders: 18,
    tags: ["Content", "Blog", "Tech", "SEO"],
    requirements: "Topic ideas, target keywords, and preferred writing style",
    is_active: true,
    gig_type: "service",
    collaboration_type: "individual",
    skill_level: "intermediate",
    created_at: "2024-01-12T14:00:00Z",
    updated_at: "2024-01-19T16:00:00Z",
    user: mockUsers[1],
    category: mockCategories[3],
  },
  {
    id: "gig6",
    user_id: "user3",
    category_id: "cat6",
    title: "Data analysis and visualization for business insights",
    description:
      "Transform your raw data into actionable insights with professional data analysis and interactive visualizations using Python and Tableau.",
    price: 12000,
    delivery_days: 4,
    rating: 4.8,
    total_orders: 15,
    tags: ["Data", "Analysis", "Python", "Tableau"],
    requirements: "Dataset, analysis objectives, and preferred visualization format",
    is_active: true,
    gig_type: "service",
    collaboration_type: "individual",
    skill_level: "advanced",
    created_at: "2024-01-08T13:00:00Z",
    updated_at: "2024-01-21T17:00:00Z",
    user: mockUsers[2],
    category: mockCategories[5],
  },
]

export const mockOrders: Order[] = [
  {
    id: "order1",
    gig_id: "gig1",
    buyer_id: "user2",
    seller_id: "user1",
    amount: 15000,
    status: "completed",
    payment_status: "paid",
    delivery_date: "2024-01-22T10:00:00Z",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-22T10:00:00Z",
  },
  {
    id: "order2",
    gig_id: "gig2",
    buyer_id: "user3",
    seller_id: "user2",
    amount: 5000,
    status: "in_progress",
    payment_status: "paid",
    created_at: "2024-01-20T14:00:00Z",
    updated_at: "2024-01-20T14:00:00Z",
  },
]

export const mockReviews: Review[] = [
  {
    id: "review1",
    order_id: "order1",
    gig_id: "gig1",
    reviewer_id: "user2",
    reviewee_id: "user1",
    rating: 5,
    comment: "Excellent work! The website exceeded my expectations. Alice was professional and delivered on time.",
    created_at: "2024-01-22T12:00:00Z",
    updated_at: "2024-01-22T12:00:00Z",
  },
]
